### PR TITLE
Review pull request

### PR DESCRIPTION
**Pull request by mprotic123**
This pull request is created in order to review a "Hello Microverse" project from Microverse curriculum.

### CODE REVIEW

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hi @mprotic123 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- Kindly fix your linter issues in your branch.
- Kindly bring a full description in your pull request description.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by AshakaE — APPROVED** [review]
## Hi @mprotic123  ,

Your project is complete! 😄  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by mprotic123** [comment]
I have merged my pull request and submited it to a Dashboard and i've got the answer "Please submit a valid Pull Request link for this project", please help me!

**Comment by mimipeshy** [comment]
Hello there @mprotic123 I have approved the project a second time, can you check now if you are able to submit the form? If not let me know in this comment section

Regards,
Peris Ndanu

**Pull request merged**
